services:
  db:
    image: postgres:16
    container_name: etudiants_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: etudiants_user
      POSTGRES_PASSWORD: etudiants_pass
      POSTGRES_DB: etudiants_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: