"""create etudiants table

Revision ID: 01d1ca0935a8
Revises: 
Create Date: 2026-07-18 11:09:46.550924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d1ca0935a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etudiants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etudiants_email'), 'etudiants', ['email'], unique=True)
    op.create_index(op.f('ix_etudiants_id'), 'etudiants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etudiants_id'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_email'), table_name='etudiants')
    op.drop_table('etudiants')
    # ### end Alembic commands ###
