"""add telephone column to etudiants

Revision ID: d00034013ae6
Revises: 01d1ca0935a8
Create Date: 2026-07-18 11:22:54.606754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00034013ae6'
down_revision: Union[str, Sequence[str], None] = '01d1ca0935a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column('telephone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etudiants', 'telephone')
    # ### end Alembic commands ###
